[build]
  functions = "functions"
  publish = "public"

[dev]
  functions = "functions"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200

[[redirects]]
  from = "/payment/*"
  to = "/.netlify/functions/payment/:splat"
  status = 200

[[redirects]]
  from = "/accomodations/*"
  to = "/.netlify/functions/accomodations/:splat"
  status = 200

<<<<<<< HEAD
=======
[[redirects]]
  from = "/room_types/*"
  to = "/.netlify/functions/room_types/:splat"
  status = 200

>>>>>>> a51d74dabf21556acbb5865764ca262d461d4f92
[functions]
  node_bundler = "esbuild"