[build]
  functions = "functions"
  publish = "public"

[dev]
  functions = "functions"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200

[[redirects]]
  from = "/payment/*"
  to = "/.netlify/functions/payment/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"