[build]
  functions = "functions"
  publish = "public"

[dev]
  functions = "functions"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200

[[redirects]]
  from = "/payment/*"
  to = "/.netlify/functions/payment/:splat"
  status = 200

[[redirects]]
  from = "/accomodations/*"
  to = "/.netlify/functions/accomodations/:splat"
  status = 200

[[redirects]]
  from = "/room_types/*"
  to = "/.netlify/functions/room_types/:splat"
  status = 200

[[redirects]]
  from = "/bookings/*"
  to = "/.netlify/functions/bookings/:splat"
  status = 200

[[redirects]]
  from = "/reviews/*"
  to = "/.netlify/functions/reviews/:splat"
  status = 200

[[redirects]]
  from = "/favourites/*"
  to = "/.netlify/functions/favourites/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:5173, https://booknest-j3la.onrender.com"
    Access-Control-Allow-Headers = "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"